<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <GameDir>C:\Program Files (x86)\Steam\steamapps\common\Slay the Spire 2</GameDir>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="sts2"><HintPath>$(GameDir)\data_sts2_windows_x86_64\sts2.dll</HintPath></Reference>
    <Reference Include="GodotSharp"><HintPath>$(GameDir)\data_sts2_windows_x86_64\GodotSharp.dll</HintPath></Reference>
    <Reference Include="0Harmony"><HintPath>$(GameDir)\data_sts2_windows_x86_64\0Harmony.dll</HintPath></Reference>
  </ItemGroup>

</Project>
